name: IndexNow Auto Submit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Submit sitemap to IndexNow
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: https://www.petartlab.net/sitemap.xml
          endpoint: https://api.indexnow.org
          key: 0c0a7a36580b493e8a0f590d007781ae
          key-location: https://www.petartlab.net/0c0a7a36580b493e8a0f590d007781ae.txt
